import type { ReportTemplateProps } from './types.ts';
import { format } from 'date-fns';

export function ModernTemplate({ data }: ReportTemplateProps) {
  return (
    <div className="w-full bg-white text-slate-900 p-8" id="report-content">
      {/* Header */}
      <div className="flex justify-between items-start mb-12 border-b pb-6">
        <div>
           {data.companyInfo.logoUrl && (
             <img src={data.companyInfo.logoUrl} alt="Logo" className="h-10 w-auto mb-4" />
           )}
           <h1 className="text-3xl font-bold text-slate-900 tracking-tight">{data.title}</h1>
           <p className="text-slate-500 mt-1">{data.subTitle}</p>
        </div>
        <div className="text-right">
           <h2 className="text-xl font-semibold text-slate-800">{data.companyInfo.name}</h2>
           <div className="text-sm text-slate-500 space-y-1 mt-2">
             <p>{data.companyInfo.address}</p>
             <p>{data.companyInfo.email}</p>
             <p>{data.companyInfo.phone}</p>
           </div>
        </div>
      </div>

      {/* Meta Bar */}
      <div className="flex justify-between items-center bg-slate-50 p-4 rounded-lg mb-8 text-sm">
         <div className="grid grid-cols-2 gap-x-8 gap-y-1">
            <span className="text-slate-500">Generated On:</span>
            <span className="font-medium">{format(data.generatedAt, 'MMM dd, yyyy HH:mm')}</span>
            <span className="text-slate-500">Generated By:</span>
            <span className="font-medium">{data.generatedBy}</span>
         </div>
         <div className="text-right">
            <span className="text-slate-500 block">Reporting Period</span>
            <span className="font-medium">
                {data.dateRange.from ? format(data.dateRange.from, 'MMM dd, yyyy') : 'Start'} 
                {' - '}
                {data.dateRange.to ? format(data.dateRange.to, 'MMM dd, yyyy') : 'Present'}
            </span>
         </div>
      </div>

      {/* Metrics Grid */}
      {data.metrics.length > 0 && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
            {data.metrics.map((metric, i) => (
                <div key={i} className="bg-white border rounded-xl p-4 shadow-sm">
                    <p className="text-sm text-slate-500 mb-1">{metric.label}</p>
                    <p className="text-2xl font-bold text-slate-900">{metric.value}</p>
                    {metric.change !== undefined && (
                        <p className={`text-xs mt-1 ${metric.change >= 0 ? 'text-emerald-600' : 'text-rose-600'}`}>
                            {metric.change >= 0 ? '+' : ''}{metric.change}% vs prev period
                        </p>
                    )}
                </div>
            ))}
        </div>
      )}

      {/* Data Table */}
      <div className="mb-8">
        <h3 className="text-lg font-semibold mb-4 text-slate-800">Detailed Breakdown</h3>
        <table className="w-full text-sm text-left">
            <thead className="bg-slate-100 text-slate-700 uppercase font-semibold text-xs">
                <tr>
                    {data.tableHeaders.map((header, i) => (
                        <th key={i} className="px-4 py-3 border-b border-slate-200">{header}</th>
                    ))}
                </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
                {data.tableRows.map((row, i) => (
                    <tr key={i} className="hover:bg-slate-50/50">
                        {row.map((cell, j) => (
                            <td key={j} className="px-4 py-3 text-slate-600 border-b border-slate-100">
                                {cell}
                            </td>
                        ))}
                    </tr>
                ))}
            </tbody>
        </table>
      </div>

      {/* Footer */}
      <div className="border-t pt-6 text-center text-xs text-slate-400 mt-auto print:fixed print:bottom-0 print:w-full print:left-0">
          <p>{data.footerText || 'Confidential Data - For Internal Use Only'}</p>
          <p className="mt-1">Page 1 of 1</p>
      </div>
    </div>
  );
}
